# Generated by Django 4.2.13 on 2024-07-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('appointment_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FamilyPlanningInfo',
        ),
    ]
