# Generated by Django 4.2.13 on 2024-07-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_sms', '0002_appointment_delete_familyplanninginfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_fname',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_lname',
            field=models.CharField(default='lname', max_length=100),
            preserve_default=False,
        ),
    ]
